export type Frame = {
  id: string;
  name: string;
  frame_url: string;
  thumbnail_url: string;
  sort_order: number;
  is_active: boolean;
};
export type Campaign = {
  id: string;
  name: string;
  slug: string;
  short_code?: string;
  organization_name: string;
  title: string;
  description: string;
  logo_url: string;
  cover_url: string;
  primary_color: string;
  secondary_color: string;
  accent_color: string;
  event_date_text: string;
  location: string;
  status: "draft" | "published" | "ended" | "archived";
  start_at: string | null;
  end_at: string | null;
  require_name: boolean;
  require_email: boolean;
  show_name_on_image: boolean;
  enable_face_centering: boolean;
  enable_share: boolean;
  enable_facebook: boolean;
  enable_png: boolean;
  enable_jpg: boolean;
  allow_duplicate_emails: boolean;
  allow_after_end: boolean;
  share_text: string;
  privacy_text: string;
  cta_text: string;
  filename_prefix: string;
  thank_you_text: string;
  name_position: "top" | "bottom" | "custom";
  name_color: string;
  name_font: string;
  name_font_size: number;
  frames: Frame[];
  created_at?: string;
};
export type Participant = {
  id: string;
  campaign_id: string;
  name: string;
  email: string;
  registered_at: string;
  marketing_consent: boolean;
  generated_at: string | null;
  downloaded_at: string | null;
  shared_at: string | null;
};
export type Event = {
  id: string;
  campaign_id: string;
  participant_id: string | null;
  event_type: string;
  frame_id: string | null;
  created_at: string;
};
