-- Run in the Supabase SQL editor. Visitor image columns intentionally do not exist.
create extension if not exists pgcrypto;
create table public.profiles(id uuid primary key references auth.users on delete cascade,email text not null,full_name text not null default '',role text not null default 'admin' check(role='admin'),created_at timestamptz not null default now());
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role='admin')$$;
create table public.campaigns(
id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),organization_name text not null,title text not null,description text not null default '',logo_url text not null default '',cover_url text not null default '',primary_color text not null default '#155eef',secondary_color text not null default '#f8fafc',accent_color text not null default '#12b76a',event_date_text text not null default '',location text not null default '',status text not null default 'draft' check(status in('draft','published','ended','archived')),start_at timestamptz,end_at timestamptz,require_name boolean not null default true,require_email boolean not null default true,show_name_on_image boolean not null default false,enable_face_centering boolean not null default false,enable_share boolean not null default true,enable_facebook boolean not null default true,enable_png boolean not null default true,enable_jpg boolean not null default true,allow_duplicate_emails boolean not null default true,allow_after_end boolean not null default false,share_text text not null default '',privacy_text text not null default '',cta_text text not null default 'Generate My Frame',filename_prefix text not null default 'Framezi',thank_you_text text not null default '',name_position text not null default 'bottom' check(name_position in('top','bottom','custom')),name_color text not null default '#ffffff',name_font text not null default 'Arial' check(name_font in('Arial','Georgia','Verdana')),name_font_size integer not null default 70 check(name_font_size between 20 and 160),created_by uuid references auth.users,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_at is null or start_at is null or end_at>start_at));
create table public.campaign_frames(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references campaigns on delete cascade,name text not null,frame_url text not null,thumbnail_url text not null default '',sort_order integer not null default 0,is_active boolean not null default true,created_at timestamptz not null default now());
create table public.participants(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references campaigns on delete cascade,name text not null check(length(name)<=60),email text not null check(length(email)<=150),consent boolean not null check(consent=true),marketing_consent boolean not null default false,registered_at timestamptz not null default now(),generated_at timestamptz,downloaded_at timestamptz,shared_at timestamptz);
create index participants_campaign_email on participants(campaign_id,lower(email));
create table public.campaign_events(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references campaigns on delete cascade,participant_id uuid references participants on delete cascade,event_type text not null check(event_type in('campaign_view','registration','photo_selected','frame_selected','generated','download_png','download_jpg','share','facebook_click')),frame_id uuid references campaign_frames on delete set null,generation_id uuid,created_at timestamptz not null default now());
create unique index events_dedup on campaign_events(participant_id,event_type,generation_id) where generation_id is not null;
create index events_campaign_date on campaign_events(campaign_id,created_at);
create index participants_date on participants(registered_at);
create table public.rate_limits(key text primary key,count integer not null default 1,expires_at timestamptz not null default now()+interval '1 hour');
alter table profiles enable row level security;alter table campaigns enable row level security;alter table campaign_frames enable row level security;alter table participants enable row level security;alter table campaign_events enable row level security;alter table rate_limits enable row level security;
create policy profiles_read on profiles for select to authenticated using(id=auth.uid());
create policy campaign_public on campaigns for select to anon,authenticated using(status in('published','ended'));
create policy campaign_admin on campaigns for all to authenticated using(is_admin()) with check(is_admin());
create policy frames_public on campaign_frames for select to anon,authenticated using(is_active and exists(select 1 from campaigns c where c.id=campaign_id and c.status in('published','ended')));
create policy frames_admin on campaign_frames for all to authenticated using(is_admin()) with check(is_admin());
create policy participants_admin on participants for select to authenticated using(is_admin());
create policy events_admin on campaign_events for select to authenticated using(is_admin());
-- Public metadata writes go through validated, rate-limited server endpoints. No anonymous reads or direct writes.
revoke all on participants,campaign_events,rate_limits from anon;
revoke insert,update,delete on participants,campaign_events from authenticated;
grant select on participants,campaign_events to authenticated;
create function public.check_rate_limit(p_key text,p_limit integer) returns boolean language plpgsql security definer set search_path=public as $$declare n integer;begin delete from rate_limits where expires_at<now();insert into rate_limits(key) values(p_key) on conflict(key) do update set count=rate_limits.count+1 returning count into n;return n<=p_limit;end$$;
create function public.register_participant(p_campaign uuid,p_name text,p_email text,p_marketing boolean) returns uuid language plpgsql security definer set search_path=public as $$declare c campaigns;pid uuid;begin select * into c from campaigns where id=p_campaign for update;if not found or c.status<>'published' or c.start_at>now() or (c.end_at<now() and not c.allow_after_end) then raise exception 'Campaign unavailable';end if;if length(p_name)>60 or length(p_email)>150 or (c.require_name and length(trim(p_name))=0) or (c.require_email and p_email='') or (p_email<>'' and p_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$') then raise exception 'Invalid details';end if;if not c.allow_duplicate_emails and p_email<>'' and exists(select 1 from participants where campaign_id=p_campaign and lower(email)=lower(p_email)) then raise exception 'Email already registered';end if;insert into participants(campaign_id,name,email,consent,marketing_consent) values(p_campaign,trim(p_name),lower(trim(p_email)),true,p_marketing) returning id into pid;insert into campaign_events(campaign_id,participant_id,event_type) values(p_campaign,pid,'registration');return pid;end$$;
create function public.record_event(p_campaign uuid,p_participant uuid,p_event text,p_frame uuid,p_generation uuid) returns void language plpgsql security definer set search_path=public as $$declare c campaigns;inserted integer;begin select * into c from campaigns where id=p_campaign;if not found or c.status not in('published','ended') then raise exception 'Campaign unavailable';end if;if p_event='campaign_view' then insert into campaign_events(campaign_id,event_type) values(p_campaign,p_event);return;end if;if not exists(select 1 from participants where id=p_participant and campaign_id=p_campaign) then raise exception 'Invalid participant';end if;if p_frame is not null and not exists(select 1 from campaign_frames where id=p_frame and campaign_id=p_campaign and is_active) then raise exception 'Invalid frame';end if;if p_event in('generated','download_png','download_jpg','share','facebook_click') and p_generation is null then raise exception 'Generation required';end if;if p_event='generated' and (p_frame is null or c.status<>'published' or (c.end_at<now() and not c.allow_after_end)) then raise exception 'Generation unavailable';end if;if p_event in('download_png','download_jpg','share','facebook_click') and not exists(select 1 from campaign_events where participant_id=p_participant and generation_id=p_generation and event_type='generated') then raise exception 'Generate first';end if;insert into campaign_events(campaign_id,participant_id,event_type,frame_id,generation_id) values(p_campaign,p_participant,p_event,p_frame,p_generation) on conflict do nothing;get diagnostics inserted=row_count;if inserted>0 then update participants set generated_at=case when p_event='generated' then coalesce(generated_at,now()) else generated_at end,downloaded_at=case when p_event in('download_png','download_jpg') then coalesce(downloaded_at,now()) else downloaded_at end,shared_at=case when p_event in('share','facebook_click') then coalesce(shared_at,now()) else shared_at end where id=p_participant;end if;end$$;
create function public.save_campaign(p_campaign jsonb) returns uuid language plpgsql security invoker set search_path=public as $$declare c campaigns;f jsonb;cid uuid;begin if not is_admin() then raise exception 'Unauthorized';end if;if jsonb_array_length(p_campaign->'frames')>3 then raise exception 'Too many frames';end if;cid=coalesce(nullif(p_campaign->>'id','')::uuid,gen_random_uuid());select * into c from jsonb_populate_record(null::campaigns,p_campaign-'frames'-'created_at'||jsonb_build_object('id',cid,'created_by',auth.uid(),'created_at',now(),'updated_at',now()));insert into campaigns select c.* on conflict(id) do update set name=excluded.name,slug=excluded.slug,organization_name=excluded.organization_name,title=excluded.title,description=excluded.description,logo_url=excluded.logo_url,cover_url=excluded.cover_url,primary_color=excluded.primary_color,secondary_color=excluded.secondary_color,accent_color=excluded.accent_color,event_date_text=excluded.event_date_text,location=excluded.location,status=excluded.status,start_at=excluded.start_at,end_at=excluded.end_at,require_name=excluded.require_name,require_email=excluded.require_email,show_name_on_image=excluded.show_name_on_image,enable_face_centering=excluded.enable_face_centering,enable_share=excluded.enable_share,enable_facebook=excluded.enable_facebook,enable_png=excluded.enable_png,enable_jpg=excluded.enable_jpg,allow_duplicate_emails=excluded.allow_duplicate_emails,allow_after_end=excluded.allow_after_end,share_text=excluded.share_text,privacy_text=excluded.privacy_text,cta_text=excluded.cta_text,filename_prefix=excluded.filename_prefix,thank_you_text=excluded.thank_you_text,name_position=excluded.name_position,name_color=excluded.name_color,name_font=excluded.name_font,name_font_size=excluded.name_font_size,updated_at=now();delete from campaign_frames where campaign_id=cid and id not in(select (value->>'id')::uuid from jsonb_array_elements(p_campaign->'frames'));for f in select value from jsonb_array_elements(p_campaign->'frames') loop if exists(select 1 from campaign_frames where id=(f->>'id')::uuid and campaign_id<>cid) then raise exception 'Frame belongs to another campaign';end if;insert into campaign_frames(id,campaign_id,name,frame_url,thumbnail_url,sort_order,is_active) values((f->>'id')::uuid,cid,f->>'name',f->>'frame_url',f->>'thumbnail_url',(f->>'sort_order')::integer,(f->>'is_active')::boolean) on conflict(id) do update set name=excluded.name,frame_url=excluded.frame_url,thumbnail_url=excluded.thumbnail_url,sort_order=excluded.sort_order,is_active=excluded.is_active;end loop;return cid;end$$;
revoke all on function check_rate_limit(text,integer),register_participant(uuid,text,text,boolean),record_event(uuid,uuid,text,uuid,uuid) from public,anon,authenticated;
grant execute on function check_rate_limit(text,integer),register_participant(uuid,text,text,boolean),record_event(uuid,uuid,text,uuid,uuid) to service_role;
revoke all on function save_campaign(jsonb) from public,anon;grant execute on function save_campaign(jsonb) to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('campaign-assets','campaign-assets',true,4194304,array['image/png','image/jpeg','image/webp']) on conflict(id) do nothing;
create policy assets_read on storage.objects for select to anon,authenticated using(bucket_id='campaign-assets');
create policy assets_admin on storage.objects for all to authenticated using(bucket_id='campaign-assets' and public.is_admin()) with check(bucket_id='campaign-assets' and public.is_admin());
